### ISSUE TITLE
FRP:  deposit to/withdraw from vault

### ISSUE THREAD

**Issue by Majorfi** [yearn/yCRV#33]
### What is your proposal 🚀
Add a deposit/withdraw button on the `holding` page, next to your holdings (bottom table)

### What does this solve ? 🛠
Will allow people to deposit/withdraw tokens directly from y.finance

### More 🔎
*N/A*

**Comment by ai-slave** [comment]
Can't we just put a link to yearn.finance so it stays the main page to manage the vaults? 
Did not found a component to use in this place and transforming deposit-withdrawal thing (from yearn.finance) into something unified sounds like an overkill for this i'd say.
